---
- name: Ensure ~/.local/share/fonts directory exists
  ansible.builtin.file:
    path: "{{ home }}/.local/share/fonts"
    state: directory
    mode: "0755"

- name: Ensure dependencies are installed
  ansible.builtin.package:
    name: unzip
    state: present
  become: true

- name: Download JetBrainsMono Nerd Font
  ansible.builtin.get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/JetBrainsMono.zip
    dest: /tmp/jb.zip
    mode: "0644"

- name: Extract JetBrainsMono into ~/.local/share/fonts
  ansible.builtin.unarchive:
    src: /tmp/jb.zip
    remote_src: true
    dest: "{{ home }}/.local/share/fonts"

- name: Download Hasklig Nerd Font
  ansible.builtin.get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hasklig.zip
    dest: /tmp/hasklig.zip
    mode: "0644"

- name: Extract Hasklig into ~/.local/share/fonts
  ansible.builtin.unarchive:
    src: /tmp/hasklig.zip
    remote_src: true
    dest: "{{ home }}/.local/share/fonts"

- name: Install other fonts
  ansible.builtin.package:
    name: "{{ font_packages }}"
    state: present
  become: true
