---
- name: Archlinux
  block:
    - name: Configure pacman [Arch]
      ansible.builtin.template:
        src: pacman.conf.j2
        dest: /etc/pacman.conf
        mode: "0644"
        owner: root
        group: root
        backup: true

    - name: Configure makepkg [Arch]
      ansible.builtin.template:
        src: makepkg.conf.j2
        dest: /etc/makepkg.conf
        mode: "0644"
        owner: root
        group: root
        backup: true

    - name: Ensure system is up-to-date [Arch]
      ansible.builtin.pacman:
        update_cache: true
        upgrade: true
  when: ansible_distribution == "Archlinux"
  become: true

- name: Fedora
  block:
    - name: Configure dnf [Fedora]
      ansible.builtin.template:
        src: dnf.conf.j2
        dest: /etc/dnf/dnf.conf
        mode: "0644"
        owner: root
        group: root
        backup: true

    - name: Ensure system is up-to-date [Fedora].
      ansible.builtin.dnf:
        update_cache: true
        name: "*"
        state: latest

    - name: Autoremove unneeded packages.
      ansible.builtin.dnf:
        autoremove: true
  when: ansible_distribution == "Fedora"
  become: true
