---
- name: Enable the sway-extras COPR
  community.general.copr:
    name: alebastr/sway-extras
    state: enabled
  become: true

- name: Ensure required packages are installed
  ansible.builtin.dnf:
    name:
      - sway
      - waybar
      - mako
      - swaylock
      - swayidle
      - xdg-desktop-portal-wlr
      - rofi-wayland
      - wev
      - brightnessctl
      - grimshot
      - swappy
      - network-manager-applet
      - blueman
      - wob
      - wf-recorder
      - slurp
    state: present
  become: true
