---
- name: Ensure podman is installed
  ansible.builtin.package:
    name:
      - podman
      - podman-docker
      - podman-compose
      - buildah
    state: present

- name: Ensure distrobox is installed (Fedora)
  ansible.builtin.dnf:
    name: distrobox
    state: present
  when: ansible_distribution == "Fedora"

- name: Ensure distrobox is installed (Archlinux)
  import_tasks: tasks/aur.yml
  vars:
    aur_packages:
      - distrobox
  when: ansible_distribution == "Archlinux"
  become: false

- name: Rootless Podman | Install required for Archlinux
  community.general.pacman:
    name:
      - fuse-overlayfs
      - slirp4netns
    state: present
  when: ansible_distribution == "Archlinux"

- name: Rootless Podman | Allocate UIDs for the current user
  ansible.builtin.lineinfile:
    path: /etc/subuid
    regexp: "^{{ ansible_user_id }}"
    line: "{{ ansible_user_id }}:100000:65536"
    create: true
    mode: "0644"
  when: ansible_distribution != "Fedora"

- name: Rootless Podman | Allocate GIDs for the current user's group
  ansible.builtin.lineinfile:
    path: /etc/subgid
    regexp: "^{{ ansible_user_id }}"
    line: "{{ ansible_user_id }}:100000:65536"
    create: true
    mode: "0644"
  when: ansible_distribution != "Fedora"

- name: Update podman's search registries
  ansible.builtin.lineinfile:
    path: /etc/containers/registries.conf
    backrefs: true
    regexp: "^(#\ )?(unqualified-search-registries)\ =\ .*$"
    line: '\2 = ["docker.io", "registry.fedoraproject.org", "registry.access.redhat.com", "quay.io"]'
    backup: true

    #- name: Install VirtualBox
    #ansible.builtin.import_role:
    #name: virtualbox

- name: Install libvirt
  ansible.builtin.import_role:
    name: ansible-role-libvirt
  vars:
    libvirt_users_in_libvirt_group:
      - "{{ ansible_env.USER }}"

- name: Ensure Vagrant is installed
  ansible.builtin.package:
    name: vagrant
    state: present

- name: Ensure the vagrant-libvirt plugin is installed
  ansible.builtin.command: vagrant plugin install vagrant-libvirt
  changed_when: true
  become: false

- name: podman pull container images for distrobox containers
  containers.podman.podman_image:
    name: "{{ item.image }}"
    tag: "{{ item.tag }}"
    pull: true
  loop:
    - image: archlinux
      tag: latest
    - image: fedora
      tag: rawhide
  become: false

- name: Create distrobox containers
  ansible.builtin.command: "distrobox-create --image {{ item.image }} -n {{ item.name }}"
  changed_when: true
  loop:
    - image: archlinux:latest
      name: arch
    - image: fedora:rawhide
      name: fedora
  become: false
