---
# Install tmux and the tmux plugin manager https://github.com/tmux-plugins/tpm)

- name: tmux setup | Ensure tmux is installed.
  package:
    name: tmux
    state: present
  become: true

- name: tmux setup | Clone tpm plugin manager.
  git:
    repo: "https://github.com/tmux-plugins/tpm.git"
    dest: "{{ ansible_user_dir }}/.config/tmux/plugins/tpm"
    version: master
